### PR TITLE
Updates referral search description

### PR DESCRIPTION
**Pull request by GolfyMcG**

### CODE REVIEW

**Comment by GolfyMcG** [comment]
@dleve123 just saw your comment come in so I've added it here!

**Comment by dleve123** [comment]
:+1: - but it's also my diff :) – @switzersc would be curious to get your feedback on effective API documentation, for example, do you think this docs refactoring is valuable? I have a feeling that you have some experience with this!

**Comment by switzersc** [comment]
@dleve123 I just commented in the closed PR, but I'll move here since we've got this one open now:

I think POST is most appropriate here, and I would expect a body to be sent with the data rather than queries in the url. I was assuming that the documentation used query params here (which would still work with a POST request) for simplicity's sake with curl, but it'd be more conventional to have this curl request use the `--data` flag (check out [this SO answer](http://superuser.com/questions/149329/what-is-the-curl-command-line-syntax-to-do-a-post-request)).

**Comment by switzersc** [comment]
I think docs are really important, and think updating this description is valuable. :+1:

**Comment by switzersc** [comment]
Also, if we're going to have more than one client using our API and if we're going to pitch the API as one our features, I think it'd be worth putting a bit more effort into the docs :) It's not pressing at the moment, but maybe we can discuss this at the next roadmap meeting.

**Comment by dleve123** [comment]
Agreed that if we get more biz transaction on the API that we should have a
more formal approach to the documentation. I know a lot of people write
docs in the code itself so that it's hard to allow the docs and code from
getting out of date, so maybe something like that would be a good fit.

On Wed, Jan 20, 2016 at 11:09 AM Shelby Switzer <notifications@github.com>
wrote:

> Also, if we're going to have more than one client using our API and if
> we're going to pitch the API as one our features, I think it'd be worth
> putting a bit more effort into the docs :) It's not pressing at the moment,
> but maybe we can discuss this at the next roadmap meeting.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/healthify/api_docs/pull/2#issuecomment-173252368>.
>
-- 
Daniel Levenson
Chief Technology Officer
Healthify <http://www.healthify.us/>

**Pull request merged**
